name: ❓ Question
description: Ask a question about using @ddevkim/carousel-circular-3d
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much context as possible.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: "How do I..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve?
      placeholder: "I'm building a photo gallery and want to..."
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What solutions have you already attempted?
      placeholder: |
        I tried...
        I looked at...

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample (Optional)
      description: If relevant, please provide code showing what you're working with
      render: tsx
      placeholder: |
        import { CarouselCircular } from '@ddevkim/carousel-circular-3d';

        // Your code here

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
